# App
spring.application.name=${SPRING_APP_NAME}-dev
server.port=${HOST_PORT}
spring.log.level=${SPRING_LOG_LEVEL}

# Service Discovery
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Security
jwt.secret=${SPRING_JWT_SECRET}
jwt.issuer=${SPRING_JWT_ISSUER}
jwt.public=${SPRING_JWT_PUBLIC}

# OpenAPI / Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.persistAuthorization=true
springdoc.swagger-ui.urlsPrimaryName=Store Manager
springdoc.swagger-ui.urls[0].name=Store Manager
springdoc.swagger-ui.urls[0].url=/v3/api-docs
springdoc.swagger-ui.urls[1].name=Carts
springdoc.swagger-ui.urls[1].url=/carts/v3/api-docs
springdoc.swagger-ui.urls[2].name=Products
springdoc.swagger-ui.urls[2].url=/products/v3/api-docs
springdoc.override-with-generic-response=false
springdoc.openapi.components.security-schemes.bearerAuth.type=http
springdoc.openapi.components.security-schemes.bearerAuth.scheme=bearer
springdoc.openapi.components.security-schemes.bearerAuth.bearerFormat=JWT
springdoc.openapi.security[0].bearerAuth=
