# Documentation Metadata
app.openapi.info.title=Store Manager Microservice API
app.openapi.info.version=v0.1
app.openapi.info.description=This microservice coordinates store operations between Store domain microservices.
