# Documentation Metadata
springdoc.openapi.info.title=Store Manager Microservice API
springdoc.openapi.info.version=v0.1
springdoc.openapi.info.description=This microservice coordinates store \
                                   operations between Store domain microservices.
