# Documentation Metadata
springdoc.openapi.info.title=Store Manager Microservice API
springdoc.openapi.info.version=v0.1
springdoc.openapi.info.description=This microservice coordinates store operations between Store domain microservices.

# Actuator
management.info.env.enabled=true
info.app.name=${spring.application.name}
info.app.description=${springdoc.openapi.info.title}
info.app.environment=${spring.profiles.active}
